### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DMC_Portuguese_Group_402#48]
**Reasoning:**
Great work on the report! In order to improve this, you can:
- [x] Expand on the limitations of your approach
- [x] Expand on the future directions

**Mechanics:**
Very organized and concise README, great job! Nothing to add in terms of mechanics.

**Viz:**
Very clear and relevant visualizations in general. Great job!
- [x] All I want to point out is that Figure 3 is a bit too cluttered to read properly. I would suggest providing a link in the report to this whole figure, and only including the correlation graphs that display interesting patterns you mention below Figure 3.
- [x] Last graph must be named Figure 5. Also, the text should be bigger here to be readable.

**Writing:**
- [x] I suggest avoiding point form in your explanation of Figure 4.

**Comment by sgauravm** [comment]
This [commit](https://github.com/UBC-MDS/DMC_Portuguese_Group_402/commit/e598ac5609b12e77ade8a492dc15a38afb7dfd4d) solves the Reasoning issue of expanding on Future work and limitations
