### ISSUE TITLE
Master Checklist

### ISSUE THREAD

**Issue by sgauravm** [UBC-MDS/DMC_Portuguese_Group_402#58]
- [x] Docker file - To be created by each one of us for learning purpose

- [x] Dependency Image - Gaurav

- [x] Visualization feedback (Part 1 - Till Figure 4) - Shiying

- [x] Visualisation feedback(Part 2 -  Figure 5,Tabel 1 and Table2 ) - Karlos

- [x] Improving makefile if there is an issue - Can be taken up voluntarily after the above tasks are done
